= Contributing to the Linux Counter Project
:idprefix:
:icons: font
:toc:

== General Terms

* You must contribute your commits under the link:LICENSE[Apache License v2]. +
PRs with other license texts will not be accepted.
* GitHub Actions must pass. +
If they cannot pass, please specify why (in the PR description).

== Code Style

=== Java

checkstyle will be provided and executed in the verify phase.

=== JavaScript / Typescript

Open to Contributions.

=== Posix ShellScript (Client)

shfmt and shellcheck must run.

=== Documentation

Documentation must be done in AsciiDoc, not Markdown.

Please use one line per sentence.

== PR and Commit descriptions

Please prefix with `[#issueID]` like this:

`[#12] description of WHAT is done`

== Development environment

Any IDE can be used.
This section also contains examples of how to start local development servers with hot deployment for faster development.

=== Java

To start the hot-deploy application server (OpenLiberty), use this command:

[source,bash]
----
./mvnw liberty:dev -pl web/rest-v1 -am
----

Any changes you make will now be reflected live on the server.

You can of course also use your IDE‘s application server integration and develop on any other MicroProfile3/JakartaEE8 application server.

[TIP]
.Running integration tests
====
You can press kbd:[Enter] any time to run the integration tests from the maven project.
====

