= The Unix Counter
:idprefix:
:icons: font
:toc: macro

image:https://img.shields.io/badge/license-Apachev2-green[]
link:https://github.com/LinuxCounter/unixcounter/actions/workflows/maven.yaml[image:https://github.com/LinuxCounter/unixcounter/actions/workflows/maven.yaml/badge.svg[Maven CI]]
link:https://renovatebot.com[image:https://img.shields.io/badge/renovate-enabled-brightgreen.svg[Renovate]]
link:https://openliberty.io/[image:https://img.shields.io/badge/AppServer-Open%20Liberty-blue[AppServer]]

toc::[]

This is the successor of the Linux Counter Project, which was abandoned in december of 2018.

== Description

In 1993, it was started as a «For fun!» project, to find out:

    How many Linux users are there? (world-wide)

The basic idea was, that people register themselves as Linux users.
Of course, this way you won't get all Linux users counted, as not every Linux user would register themself.
Most Linux users are very concerned about data privacy.
And for sure more then 90% of all Linux users never would register themselves anywhere for being statistically counted.

So the only way to get a somewhat accurate number of Linux users world-wide, is to make a guess (preferably a not too wild guess).

There is only one way to get a preferably accurate guess: statistics.

The Linux Counter was known on these domains:

* http://counter.li.org[] since 1993 until 2011 by Harald Tveit Alvestrand.
* https://www.linuxcounter.net[] since 2011 by Christin Löhner.
* https://www.unixcounter.com[] since the revival in 2021/2022 by Benjamin Marwell and Christin Löhner.

The original counter, which already started in 1993 on counter.li.org, was ran by a Non-Profit membership (organization, called «The Linux Counter Project»), which was created on the 1999-05-01. In 2011 **Alexander Mieland** took over the running counter from **Harald Tveit Alvestrand** and revived it on linuxcounter.net. In 2012 Alexander married and changed his last name to **Löhner**. In 2015 Alexander Löhner became **Christin Löhner** (transsexual woman).footnote:[https://www.christin-loehner.de/2016/01/18/a-mass-of-positive-reactions-on-my-newsletter/]

The Counter was **slashdotted** three times, while maintained by Christin Löhner.footnote:[https://linux.slashdot.org/story/11/09/10/1249257/the-linux-counter-relaunches]footnote:[https://linux.slashdot.org/story/99/02/25/117248/linux-counter-part-2]footnote:[https://linux.slashdot.org/story/99/10/23/126218/linux-counter-hits-120000] In decenmber 2018 Christin decided to shutdown the project and services of the Linuxcounter due to lack of interest. in 2021 **Benjamin Marwell** asked Christin to revive the project.

Refer to this wikipedia article: https://en.wikipedia.org/wiki/Linux_Counter[]

== Contributing

If you want to contribute, please see link:CONTRIBUTING.adoc[].

**Currently we are searching for help. We would need one or maybe two java developers to help us reviving the Counter.**
Please contact [Christin Löhner](https://github.com/christinloehner)

== Documentation

If you want to contribute, please see link:CONTRIBUTING.adoc[].

=== Installation

Prerequisites: Java 17+.

To compile, verify and package everything (server and client):

[source,bash]
.Compiling and Packaging the Linux Counter Project
----
./mvnw verify
----

To compile only the backend server:

[source,bash]
.Compiling and Packaging the Linux Counter Server Backend
----
./mvnw verify -pl web/rest-v1 -am
----

To compile only the client scripts:

[source,bash]
.Compiling and Packaging the Linux Counter Project Client Scripts
----
./mvnw verify -pl scripts -am
----

== License

The new code is licensed under the link:LICENSE[Apache License v2].


