= The Unix Counter
:idprefix:
:icons: font
:toc: macro

image:https://img.shields.io/badge/license-Apachev2-green[]
link:https://github.com/LinuxCounter/unixcounter/actions/workflows/maven.yaml[image:https://github.com/LinuxCounter/unixcounter/actions/workflows/maven.yaml/badge.svg[Maven CI]]
link:https://renovatebot.com[image:https://img.shields.io/badge/renovate-enabled-brightgreen.svg[Renovate]]
link:https://openliberty.io/[image:https://img.shields.io/badge/AppServer-Open%20Liberty-blue[AppServer]]

toc::[]

This is the successor of the Linux Counter Project, which was abandoned in december of 2018.

== Description

It was started as a «For fun!» project, to find out:

    How many Linux users are there? (world-wide)

The basic idea (for people) is to register our-selves, as being a Linux users!

Of course: this way you won't get all Linux users counted as not every Linux user would register (it-self; at the Linux counter site).

Thus: the only way to know the number, of Linux users world-wide, is to make a guess (preferably a not too wild guess) of the number, of Linux users.

=== Not making wild guesses?

There is only one way, to go: statistics; and so there we are!

Also; see this: an http://en.wikipedia.org/wiki/Linux_Counter[article of Wikipedia]
for information about a Linux Counter project.

== Documentation

If you want to contribute, please see link:CONTRIBUTING.adoc[].

=== Installation

Prerequisites: Java 17+.

To compile, verify and package everything (server and client):

[source,bash]
.Compiling and Packaging the Linux Counter Project
----
./mvnw verify
----

To compile only the backend server:

[source,bash]
.Compiling and Packaging the Linux Counter Server Backend
----
./mvnw verify -pl web/rest-v1 -am
----

To compile only the client scripts:

[source,bash]
.Compiling and Packaging the Linux Counter Project Client Scripts
----
./mvnw verify -pl scripts -am
----

== License

The new code is licensed under the link:LICENSE[Apache License v2].

== History

The Linux Counter was known on these domains:

* https://counter.li.org[] until 2012.
* https://www.linuxcounter.net[] beginning from 2012 onwards.

The original counter, which already started in 1993 on counter.li.org, was ran by a Non-Profit membership (organization, called «The Linux Counter Project»), which was created on the 1999-05-01. In 2011 **Alexander Löhner** took over the running counter from **Harald Tveit Alvestrand** and revived it on linuxcounter.net. In 2015 Alexander became Christin (transsexual woman). The Counter was ""slashdotted** three times, while maintained by Christin Löhner. In decenmber 2018 Christin decided to shutdown the project and services of the Linuxcounter due to lack of interest. in 2021 Benjamin Marwell asked Christin to revive the project.

